# Generated by Django 4.2.27 on 2026-02-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(help_text='One-liner for card display', max_length=300)),
                ('full_description', models.TextField(blank=True, help_text='Full project description for detail page')),
                ('hero_image', models.ImageField(blank=True, upload_to='portfolio/')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='portfolio/thumbs/')),
                ('demo_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('tech_tags', models.CharField(blank=True, help_text='Comma-separated: React, Django, FastAPI', max_length=500)),
                ('category', models.CharField(choices=[('client_work', 'Client Work'), ('internal_product', 'Internal Product'), ('open_source', 'Open Source'), ('research', 'Research')], default='client_work', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_title', models.CharField(blank=True, max_length=200)),
                ('person_image', models.ImageField(blank=True, upload_to='testimonials/')),
                ('quote_text', models.TextField()),
                ('linked_claim_id', models.CharField(blank=True, help_text='LinkedTrust claim ID for badge embed', max_length=50)),
                ('has_video', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='website.portfolioproject')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('short_description', models.CharField(help_text='One-liner for card display', max_length=300)),
                ('full_description', models.TextField(blank=True, help_text='Full description for detail page')),
                ('price_range', models.CharField(blank=True, help_text='e.g. "$1.5K-3K"', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('example_projects', models.ManyToManyField(blank=True, related_name='service_packages', to='website.portfolioproject')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('problem_text', models.TextField(help_text='What was the problem?')),
                ('solution_text', models.TextField(help_text='What did we build?')),
                ('result_text', models.TextField(help_text='What was the outcome?')),
                ('hero_image', models.ImageField(blank=True, upload_to='case_studies/')),
                ('client_quote', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('client_title', models.CharField(blank=True, max_length=200)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='e.g. {"cost_saved": "40%", "time": "2 weeks"}')),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='website.portfolioproject')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
