# Generated by Django 4.2.27 on 2026-02-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='badge_layout',
            field=models.CharField(choices=[('row', 'Row (horizontal rectangle — good for stacking)'), ('card', 'Card (vertical — good for standalone)')], default='row', help_text='Badge display layout', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='badge_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Badge color theme', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero (top of homepage, row layout)'), ('homepage', 'Homepage (below hero)'), ('wall', 'Badge Wall page'), ('page', 'Specific project page only')], default='homepage', help_text='Where this badge appears on the site', max_length=20),
        ),
    ]
