# Generated by Django 4.2.27 on 2026-02-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonial_badge_layout_testimonial_badge_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='One-liner for card display', max_length=300)),
                ('screenshot', models.ImageField(blank=True, upload_to='ecosystem/')),
                ('live_url', models.URLField(blank=True, help_text='Link to the live site/doc/paper')),
                ('repo_url', models.URLField(blank=True, help_text='GitHub repo if open source')),
                ('status', models.CharField(choices=[('live', 'Live'), ('active', 'Active'), ('beta', 'Beta'), ('coming', 'Coming Soon')], default='live', max_length=10)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = appears first')),
            ],
            options={
                'verbose_name': 'Ecosystem item',
                'verbose_name_plural': 'Ecosystem items',
                'ordering': ['sort_order'],
            },
        ),
    ]
