# Generated by Django 4.2.27 on 2026-02-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ecosystemitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(choices=[('client_work', 'Client Work'), ('open_source', 'Open Source'), ('research', 'Research')], default='client_work', max_length=20),
        ),
    ]
