# Generated by Django 4.2.27 on 2026-02-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_merge_internal_to_opensource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(choices=[('consulting', 'Consulting'), ('intern_placement', 'Intern Placement'), ('site_issue', 'Site Issue'), ('developer', 'Developer question'), ('other', 'Other')], default='consulting', max_length=30),
        ),
    ]
