# Generated by Django 4.2.27 on 2026-07-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contactinquiry_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedgovCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('approved', 'Approved (on the wall)'), ('pending', 'Pending review'), ('hidden', 'Hidden')], default='pending', max_length=10)),
                ('invited', models.BooleanField(default=False)),
                ('inviter', models.CharField(blank=True, max_length=100)),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
