# Generated by Django 4.2.30 on 2026-09-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_earnedgovcommitment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelUpAccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Who this code was given to",
                        max_length=120,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("uses", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LevelUp access code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LevelUpRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "organization",
                    models.CharField(
                        help_text="Company, project or idea name", max_length=200
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Site, deck, repo or doc they want us to look at",
                    ),
                ),
                (
                    "help_with",
                    models.CharField(
                        help_text="Comma-separated keys from HELP_CHOICES",
                        max_length=200,
                    ),
                ),
                ("goal", models.TextField(help_text="What they want to walk out with")),
                (
                    "wants_checkin",
                    models.BooleanField(
                        default=False, help_text="Asked for a 1-1 before the workshop"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free_small", "Free: fewer than 10 employees"),
                            ("free_nonprofit", "Free: nonprofit"),
                            ("paid", "$100: 10 or more employees"),
                        ],
                        default="free_small",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pending", "Payment pending"),
                            ("paid", "Paid"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                ("stripe_reference", models.CharField(blank=True, max_length=120)),
                (
                    "invited",
                    models.BooleanField(
                        default=False, help_text="Calendar invite and link sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.levelupaccesscode",
                    ),
                ),
            ],
            options={
                "verbose_name": "LevelUp registration",
                "ordering": ["-created_at"],
            },
        ),
    ]
