# Generated by Django 4.2.30 on 2026-09-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_levelupaccesscode_levelupregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupregistration',
            name='access_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='levelupregistration',
            name='attachment',
            field=models.FileField(
                blank=True,
                help_text='Optional document, deck, screenshot, or project artifact',
                upload_to='levelup/%Y/%m/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            'pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'md',
                            'png', 'jpg', 'jpeg', 'webp', 'zip',
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='levelupregistration',
            name='invited',
            field=models.BooleanField(
                default=False,
                help_text='Private workshop link and updated calendar invitation sent',
            ),
        ),
    ]
