# Generated by Django 4.2.30 on 2026-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_levelupregistration_attachment_and_access_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelupregistration",
            name="session",
            field=models.CharField(
                choices=[
                    ("sep16", "Wednesday, September 16, 2026"),
                    ("oct21", "Wednesday, October 21, 2026"),
                ],
                default="sep16",
                max_length=10,
            ),
        ),
    ]
