# Generated by Django 4.2.30 on 2026-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_levelupregistration_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelupregistration",
            name="attendee_notified",
            field=models.BooleanField(
                default=False,
                help_text="Confirmation to the registrant left the server",
            ),
        ),
        migrations.AddField(
            model_name="levelupregistration",
            name="team_notified",
            field=models.BooleanField(
                default=False,
                help_text="Notification to the team inbox left the server",
            ),
        ),
    ]
