# Generated by Django 4.2.27 on 2026-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_levelupregistration_attendee_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupregistration',
            name='session',
            field=models.CharField(default='sep16', help_text='Comma-separated keys from SESSION_CHOICES', max_length=40),
        ),
    ]
