# Generated by Django 4.2.27 on 2026-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_levelupregistration_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupregistration',
            name='heard_from',
            field=models.CharField(blank=True, help_text='Where they heard about LevelUp', max_length=200),
        ),
    ]
