# Generated by Django 4.2.27 on 2026-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_levelupregistration_heard_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(choices=[('client_work', 'Client Work'), ('internal_product', 'Our Products'), ('open_source', 'Open Source'), ('research', 'Research')], default='client_work', max_length=20),
        ),
    ]
