# Generated by Django 4.2.27 on 2026-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_portfolioproject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupregistration',
            name='tier',
            field=models.CharField(choices=[('free_small', 'Free: solopreneur'), ('free_nonprofit', 'Free: nonprofit'), ('paid', '$100: team')], default='free_small', max_length=20),
        ),
    ]
