# Generated by Django 4.2.27 on 2026-09-19 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_alter_levelupregistration_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupaccesscode',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levelup_codes_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
