# Generated by Django 4.2.27 on 2026-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_backfill_levelupaccesscode_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero (top of homepage, row layout)'), ('homepage', 'Homepage (below hero)'), ('wall', 'Badge Wall page'), ('page', 'Specific project page only'), ('levelup', 'LevelUp page, and under the LevelUp link on the homepage')], default='homepage', help_text='Where this badge appears on the site', max_length=20),
        ),
    ]
