# Generated by Django 4.2.27 on 2026-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_levelup_taymar_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupregistration',
            name='tier',
            field=models.CharField(choices=[('paid', '$49'), ('free_nonprofit', 'Nonprofit: free'), ('free_small', 'Solopreneur: free (retired)')], default='paid', max_length=20),
        ),
    ]
