# Generated by Django 4.2.27 on 2026-09-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_levelupregistration_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupregistration',
            name='help_with_other',
            field=models.CharField(blank=True, help_text='Free text when they pick Something else', max_length=200),
        ),
        migrations.AlterField(
            model_name='levelupregistration',
            name='goal',
            field=models.TextField(blank=True, help_text='What they want to walk out with (question retired 2026-09)'),
        ),
        migrations.AlterField(
            model_name='levelupregistration',
            name='help_with',
            field=models.CharField(blank=True, help_text='Comma-separated keys from HELP_CHOICES', max_length=200),
        ),
    ]
